config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :locals
  get     "login"    => "sessions#new"
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"
  delete  "delete"   => "users#destroy"
  resources :users

  get 'home/index'
  get 'home/bookingtours'
  get 'home/booking'
  root 'home#index'

  resources :bookings

  resources :tours do
     resources :bookings
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/news.rb
class News < ApplicationRecord
	mount_uploader :image, ImageUploader
  validates :new_name, presence: true
  validates :url, presence: true

  validates :image, file_size: { less_than: 1.megabytes }
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    #@news = News.all
    @news = News.all.page(params[:page]).per(5)
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_index_path, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_index_path, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:new_name, :image, :date, :url)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :new_name %>
    <%= form.text_field :new_name, id: :news_new_name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %><br>
  </div>

  <% if news.image? %>
    <%= image_tag news.image.thumb.url %>
    <div>
      <%= label_tag :remove_image do %>
        Remove image
        <%= form.check_box :remove_image %>
      <% end %>
    </div>
  <% end %>
</br></br>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :news_date %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :news_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
	<%= render 'inc/header' %>
<div class="container_a_12">
<!-- Account overview -->
 <div class="grid_main_r">
               <div class="module123">

<% provide(:button_text, 'Save changes') %>
<h1>Edit New</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>
</div>
</div>
 </div>  <!-- End .module -->
                <div style="clear:both;"></div>
                <div class="padding-bottom"></div>
            </div> <!-- End .grid_5 -->
            
            <div style="clear:both;"></div>

<%= render 'inc/footer'%>

app/views/news/index.html.erb
<%= render "inc/header" %>
        
    <div class="container_a_12">
             

              <div class="bottom-spacing">
                  <!-- Button--> 
                   
                  <div class="float-left">
                      <a href="<%= new_news_path %>" class="button">
                        <span>Thêm News <img src="/assets/images/plus-small.gif" alt="Thêm tin mới"></span>
                      </a>
                  </div>
              
                  <div class="clear"></div>
            </div>


            <div class="grid_a_12">
                <!-- Example table -->
                <div class="module123">
                  <h2 style="text-align: center;"><span>List News</span></h2>
                    <p id="notice"><%= notice %>
                    <div>
                      <form action="">
                        <table>
                          <thead>
                                <tr>
                                    <th style="width:4%; text-align: center;">ID</th>
                                    <th >News name</th>
                                    <th >Image</th>
                                    <th >Date</th>
                                    <th >Url</th>
                                    <th style="width:20%; text-align: center;">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                              <% @news.each do |news| %>
                                <tr>
                                    <td class="align-center"><%= news.id %></td>
                                    <td><%= news.new_name %></td>
                                     <% if news.image? %>
    
                                    <td><%= image_tag news.image.thumb.url %></td>
                                    <%else %>
                                        <td><%= news.image %></td>
                                     <% end %>
                                    <td><%= news.date %></td>
                                    <td><%= news.url %></td>
                                    <td align="center">
                                        <a href=""><%= link_to 'Edit', edit_news_path(news) %><img src="/assets/images/pencil.gif" alt="edit" /></a>
                                        
                                      <a href=""><%= link_to "Delete", news, method: :delete, data: {confirm:"Bạn có chắc chắn xóa?"} %>
                                        
                                         <img src="/assets/images/bin.gif" width="16" height="16" alt="delete" /></a>   
                                        
                                    </td>
                                </tr>
                               <% end %>
                            </tbody>
                        </table>
                        </form>
                     </div> <!-- End .module123-table-body -->
                </div> <!-- End .module123 -->
               <div class="pagination123">           
                        <div class="numbers123">
                               <%= paginate @news %>
                        </div> 
                        <div style="clear: both;"></div> 
                     </div>
               </div> <!-- End .grid_12 -->
          


            <div style="clear:both;"></div>
           
<%= render 'inc/footer'%>


<!--<p id="notice"><%= notice %></p>

<h1>News</h1>

<table>
  <thead>
    <tr>
      <th>New name</th>
      <th>Image</th>
      <th>Date</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.new_name %></td>
        <td><%= news.image %></td>
        <td><%= news.date %></td>
        <td><%= news.url %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<%= render 'inc/header' %>
<div class="container_a_12">
<!-- Account overview -->
 <div class="grid_main_r">
               <div class="module123">
     <h2><span>Thêm New</span></h2>

<br><br>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>
<div style="clear:both;"></div>
                <div class="padding-bottom"></div>
            </div> <!-- End .grid_5 -->
            
            <div style="clear:both;"></div>

<%= render 'inc/footer'%>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>New name:</strong>
  <%= @news.new_name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @news.image %>
</p>

<p>
  <strong>Date:</strong>
  <%= @news.date %>
</p>

<p>
  <strong>Url:</strong>
  <%= @news.url %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>