config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :locals
  get     "login"    => "sessions#new"
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"
  delete  "delete"   => "users#destroy"
  resources :users

  get 'home/index'
  get 'home/bookingtours'
  get 'home/booking'
  root 'home#index'

  resources :bookings

  resources :tours do
     resources :bookings
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
class Tour < ApplicationRecord
  mount_uploader :image, ImageUploader
  #mount_uploaders :attachments, ImageUploader

  belongs_to :local
  has_many :bookings

  

  validates :image, file_size: { less_than: 1.megabytes }
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:show]
  # GET /tours
  # GET /tours.json
  def index
    #@tours = Tour.all
    @tours = Tour.all.page(params[:page]).per(5)
    @locals = Local.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
    @locals = Local.all
  end

  # GET /tours/1/edit
  def edit
    @locals = Local.all
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to tours_path, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to tours_path, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:tour_name, :place, :local_id, :price, :day_number, :detail, :image)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_with(model: tour, local: true) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tour_name %>
    <%= form.text_field :tour_name, id: :tour_tour_name %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place, id: :tour_place %>
  </div>


  <div class="field">
    <%= form.label :local_id %>
    <select id="local" onchange="localChanged(this)">
      <% if tour.local_id? %>
        <option value=<%= tour.local_id %> ><%= tour.local.local_name %></option>
         <% @locals.each do |local| %>
         <% if local.id != tour.local_id %>
        <option value=<%= local.id %> ><%= local.local_name %></option>
        <%end%>
      <%end%>
      

      <% else %>
        <option value="" >--Chon Local--</option>
      <% @locals.each do |local| %>
      <option value=<%= local.id %> ><%= local.local_name %></option>
      <%end%>
      <%end%>
    </select>
    <%= form.hidden_field :local_id, id: :tour_local_id %>
  </div>


  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :tour_price %>
  </div>

  <div class="field">
    <%= form.label :day_number %>
    <%= form.text_field :day_number, id: :tour_day_number %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail, id: :tour_detail %>
  </div>

 <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %><br>
  </div>

  <% if tour.image? %>
    <%= image_tag tour.image.thumb.url %>
    <div>
      <%= label_tag :remove_image do %>
        Remove image
        <%= form.check_box :remove_image %>
      <% end %>
    </div>
  <% end %>


</br></br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>









 <script language="javascript">
            // Hàm xử lý khi thẻ select thay đổi giá trị được chọn
            // obj là tham số truyền vào và cũng chính là thẻ select
            function localChanged(obj)
            {
                  var id = document.getElementById('tour_local_id');
                  var val = obj.value;
                  id.value = val;
            }
 
        </script>
 
        </script>

app/views/tours/edit.html.erb
<%= render 'inc/header' %>
<div class="container_a_12">
<!-- Account overview -->
 <div class="grid_main_r">
               <div class="module123">
<% provide(:button_text, 'Save changes') %>
<h1>Edit Tours</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<%= render 'form', tour: @tour %>

<%= link_to 'Back', tours_path %>
 </div>
</div>
 </div>  <!-- End .module -->
                <div style="clear:both;"></div>
                <div class="padding-bottom"></div>
            </div> <!-- End .grid_5 -->
            
            <div style="clear:both;"></div>

<%= render 'inc/footer'%>

app/views/tours/index.html.erb
<%= render "inc/header" %>
        
    <div class="container_a_12">
             

              <div class="bottom-spacing">
                  <!-- Button--> 
                   
                  <div class="float-left">
                      <a href="<%= new_tour_path %>" class="button">
                        <span> Thêm Tours <img src="/assets/images/plus-small.gif" alt="Thêm tin mới"></span>
                      </a>
                  </div>
            
                  <div class="clear"></div>
            </div>


            <div class="grid_a_12">
                <!-- Example table -->
                <div class="module123">
                  <h2 style="text-align: center;"><span>List Tours</span></h2>
                    <p id="notice"><%= notice %>
                    <div>
                      <form action="">
                        <table>
                          <thead>
                                <tr>
                                    <th style="width:4%; text-align: center;">ID</th>
                                    <th style="width:4%; text-align: center;">Tour name</th>
                                    <th style="width:4%; text-align: center;">Place</th>
                                    <th style="width:4%; text-align: center;">Local</th>
                                    <th style="width:4%; text-align: center;">Price</th>
                                    <th style="width:4%; text-align: center;">Day number</th>
                                    <th style="width:46%; text-align: center;">Detail</th>
                                    <th style="width:10%; text-align: center;">Image</th>
                                    <th style="width:25%; text-align: center;">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                             <% @tours.each do |tour| %>
                                <tr>
                                    <td class="align-center"><%= tour.id %></td>
                                    <td><%= tour.tour_name %></td>
                                    <td><%= tour.place %></td>
                                    <td><%= tour.local.local_name %></td>
                                    <td><%= tour.price %></td>
                                    <td><%= tour.day_number %></td>
                                    <td><%= tour.detail %></td>
                                    <% if tour.image? %>
    
                                    <td><%= image_tag tour.image.thumb.url %></td>
                                    <%else %>
                                        <td><%= tour.image %></td>
                                     <% end %>
                                    <td align="center">
                                        <a href=""><%= link_to 'Edit', edit_tour_path(tour) %><img src="/assets/images/pencil.gif" alt="edit" /></a>
                                        
                                        <a href=""><%= link_to "Delete", tour_path(tour), method: :delete, data: {confirm:"Bạn có chắc chắn xóa?"} %>
                                      
                                        
                                         <img src="/assets/images/bin.gif" width="16" height="16" alt="delete" /></a>        
                                        
                                    
                                   
                                    </td>
                                </tr>
                               <% end %>
                            </tbody>
                        </table>
                        </form>
                     </div> <!-- End .module123-table-body -->
                </div> <!-- End .module123 -->
               <div class="pagination123">           
                        <div class="numbers123">
                               <%= paginate @tours %>
                        </div> 
                        <div style="clear: both;"></div> 
                     </div>
               </div> <!-- End .grid_12 -->
          


            <div style="clear:both;"></div>
           
<%= render 'inc/footer'%>

app/views/tours/new.html.erb
<%= render 'inc/header' %>
<div class="container_a_12">
<!-- Account overview -->
 <div class="grid_main_r">
               <div class="module123">
     <h2><span>Thêm Tours</span></h2>


<%= render 'form', tour: @tour %>

<%= link_to 'Back', tours_path %>

<div style="clear:both;"></div>
                <div class="padding-bottom"></div>
            </div> <!-- End .grid_5 -->
            
            <div style="clear:both;"></div>
            
<%= render 'inc/footer'%>

app/views/tours/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">


<!-- Mirrored from demo.createdbycocoon.com/drupal/nine/nrgtravel/1/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 22 Jan 2018 18:15:32 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>


 
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="/assets/favicon.ico" type="image/vnd.microsoft.icon" />
<meta name="Generator" content="Drupal 7 (http://drupal.org)" />
<link rel="alternate" type="application/rss+xml" title="DNTravel RSS" href="rss.xml" />
  <meta name="MobileOptimized" content="width" />
  <meta name="HandheldFriendly" content="true" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
      <title>DNTours_Booking</title>
    <style type="text/css" media="all">

<%= stylesheet_link_tag "application" %>
</style>

  <link href='http://fonts.googleapis.com/css?family=Maven+Pro:400,700,500' rel='stylesheet' type='text/css'>

    <%= javascript_include_tag "application" %>
  
</head>
<body class="html not-front not-logged-in no-sidebars page-node page-node- page-node-11 node-type-article travel" >
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '165416884141347',
      xfbml      : true,
      version    : 'v2.12'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>



      <div id="loader-wrapper"> 
      <div class="loader-content">
        <div class="cube1 t-cube"></div>
        <div class="cube2 t-cube"></div>
      </div>
    </div>
      <header class="generic-header header">
  <div class="container clearfix nopadding">
    <div id="logo">
      <a>
        <%= image_tag("logo.png", :alt => "DNTours") %>
      </a>
    </div>
          <div class="menu-button  a-menu-button">
        <span></span>
        <span></span>
        <span></span>
      </div>
      <nav class="nav ag-nav  clearfix">
          <div class="region region-main-menu">
        
  <div class="content">
    <ul class="ccn-main-menu"><li class="first leaf"><a href="/home/index#home">Home</a></li>
<li class="leaf"><a href="/home/index#about">About us</a></li>
<li class="leaf"><a href="/home/index#hot-tours">Hot tours</a></li>
<li class="leaf"><a href="/home/index#services">Services</a></li>
<li class="leaf"><a href="/home/index#gallery">Gallery</a></li>
<li class="leaf"><a href="/home/index#hotel-reviews">Reviews</a></li>
<li class="leaf"><a href="/home/index#blog">Blog</a></li>
<li class="leaf"><a href="/home/index#testimonials">Testimonials</a></li>
<li class="last leaf"><a href="/home/index#contact">Contact</a></li>
</ul>  </div>  </div>
      </nav>
      </div>
</header>
<div class="page-title">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="block-title"><%= @tour.tour_name %></h2>
                <p class="sub-title"><span class="post-meta"><%= @tour.place %><br><%= @tour.price %><br><%= @tour.day_number %></span></p>
                
      </div>
    </div>
  </div>
</div>


<div id="ccn_dConsole">
  <div class="container" style="vertical-align: middle;">
  <a href="/home/booking"><div class="datngay nav-item-serv" style="width: 100%;height: 100% ;text-align: center;font-size: 30px;"> <%= link_to "Booking", new_tour_booking_path(@tour) %></div> </a></div>
</div><!-- /#ccn_dConsole -->

<div class="blog blog-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
               <div class="row">
          <div class="col-md-12 col-sm-12 single-content post">
                     <div class="region region-content">
    <div id="block-system-main" class="block block-system">

    
  <div class="content">
    <article id="node-11" class="node node-article node-promoted node-full clearfix" about="/drupal/nine/nrgtravel/1/post/pellentesque-et-lacinia-eros-condim-entum-hendrerit-nisl-0" typeof="sioc:Item foaf:Document" role="article">
  <div class="content-media">
    <div class="field field-name-field-image field-type-image field-label-hidden"><div class="field-items"><div class="field-item even" rel="og:image rdfs:seeAlso" resource="http://demo.createdbycocoon.com/drupal/nine/nrgtravel/1/sites/default/files/styles/large_blog__900x400_/public/popup5.jpg?itok=xzrh_4Wq"><a href="pellentesque-et-lacinia-eros-condim-entum-hendrerit-nisl-0.html" class="active"><%= image_tag(@tour.image, typeof: "foaf:Image" , :alt => "image", size: "900x400") %> </a></div></div></div>      </div>


    

  <div class="content-text">
    <div class="field field-name-body field-type-text-with-summary field-label-hidden"><div class="field-items"><div class="field-item even" property="content:encoded"><p><%= @tour.detail %></p></div></div></div>  </div>


  <div class="content clearfix">
      </div>

      <div class="link-wrapper">
      <ul class="links inline"><li class="comment_forbidden first last">
        
      </li>
</ul>    </div>
  <div class="fb-comments" data-href="https://www.facebook.com/DNToursVietNam/" data-width="100%" data-numposts="5"></div>
</article>
  
  </div>
</div>
  </div>
          </div>
        </div>
          </div>
    </div>
  </div>
</div>

                            

<%= render "home/include/chat" %>   
<%= render "home/include/footer" %>  